### ISSUE TITLE
gitdb.utils.compat - Not found

### ISSUE THREAD

**Issue by FormerlyChucks** [avinassh/rockstar#105]
Trying to run this myself... After trying to `import RockStar`, I get the following traceback:

      File "/home/dio/.local/lib/python3.7/site-packages/git/compat.py", line 12, in <module>
        from gitdb.utils.compat import (
    ModuleNotFoundError: No module named 'gitdb.utils.compat'
    
From a google search result, I found [this](https://github.com/gitpython-developers/GitPython/issues/983). Maybe the `GitPython` version just needs to be updated?

**Comment by 403-Fruit** [comment]
`pip install gitdb2==3.0.1` fixed it for me

**Comment by FormerlyChucks** [comment]
Seems to fix it. @avinassh can we add `gitdb2==3.0.1` to the `requirements.txt` file?

**Comment by avinassh** [comment]
I have updated dependencies and pushed to pypi, try `pip install rockstar==0.6` and it should work. 

I am closing this issue for now, but feel free to reopen if it is still broken
