### ISSUE TITLE
Can't update number of days 

### ISSUE THREAD

**Issue by kiloreux** [avinassh/rockstar#3]
I used it to  make 300 days commit history and then on the same directory used it for 900 days , but it kept with original 300 days , and now no body will hire me :scream:  :stuck_out_tongue_winking_eye:

**Comment by avinassh** [comment]
This is unacceptable. Hang in there, I will look into this asap

**Comment by avinassh** [comment]
Just checked, it seems to be working fine here.

**Comment by kiloreux** [comment]
Could not reproduce it , i will close this issue , and go look for a job being rockstar .

**Comment by avinassh** [comment]
>  and wait for job offers.

FTFY. Rockstars don't look for jobs. Jobs find them!
