### ISSUE TITLE
WoW, add a dogecoin address, pls

### ISSUE THREAD

**Issue by hongxuchen** [avinassh/rockstar#31]
Such a nice tool!
Also, I'd suggest adding a [dogecoin address](http://dogechain.info/) of yours so that we can donate.

Such glorious, much wow! :rocket: :moon: 

![shibe](https://www.cryptocoinsnews.com/wp-content/uploads/2014/06/The-Dogecoin-Price-is-Low-and-Thats-Crazy.jpg)

**Comment by avinassh** [comment]
ha ha :stuck_out_tongue: 

here is my doge wallet address `D69E427MhM8ueJu6qEnRQBdaoPiZhD7zux`

**Comment by hongxuchen** [comment]
That's cool!

**Comment by avinassh** [comment]
received doge, much wow :sunglasses:

**Comment by hongxuchen** [comment]
:+1: Really nice tool ; but I haven't got enough dogecoin right now:-(

**Comment by avinassh** [comment]
Thats okay, no worries :grinning:
