### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by SanketDG** [avinassh/rockstar#4]
Instead of writing a script, I could really like something that can be called from the command line. Since most of the functionality is done, this can be achieved easily with the proper arguments.

**Comment by avinassh** [comment]
But Rockstar programmers write scripts! :open_mouth: 

Jokes aside, so you want something like:

```
$rockstar --days=400
```

?

**Comment by SanketDG** [comment]
> But Rockstar programmers write scripts!

Haha!

You are taking this to a whole new level!

> Jokes aside, so you want something like:
> 
> $rockstar --days=400

Yes.
