### ISSUE TITLE
Doesn't work when git config is locally set

### ISSUE THREAD

**Issue by gauravmuk** [avinassh/rockstar#56]
I executed the program and it created commits using my username and my machine name as the email id which git would never recognise as my commits.

I had to setup the user.name and user.email globally to get the commits on my name.

I don't know how this can be fixed, maybe by asking for params in the program itself?

But this was very annoying!

**Comment by avinassh** [comment]
Nope, its not annoying. It's by design. You should set the globals yourself and not in every script you write.
