### ISSUE TITLE
Profile isn't shown correctly

### ISSUE THREAD

**Issue by ningt** [avinassh/rockstar#60]
I used default `days=400` but my profile isn't shown correctly after Dec 31, 2014.

![screen shot 2015-07-27 at 2 31 43 pm](https://cloud.githubusercontent.com/assets/5404896/8899865/5e72ef30-346c-11e5-902b-c66416fdfb64.png)

But there are commits for Jan 2015 onwards.
![screen shot 2015-07-27 at 2 34 49 pm](https://cloud.githubusercontent.com/assets/5404896/8899901/b1a2baf0-346c-11e5-9a6e-1517df18eaee.png)

I'm not sure this issue is related to this repo or github, but anyone got this problem?
Found this link, but I don't this it's any of the cases: [why-are-my-contributions-not-showing-up-on-my-profile](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/)

**Comment by avinassh** [comment]
so what was the issue?

**Comment by ningt** [comment]
The issue is related to github, not rockstar. I sent an email to github support, and they updated my profile. It seems that there are something like cache for profiles, that's why my profile didn't get updated even if those commits are valid.
