### ISSUE TITLE
just can't work ,why？

### ISSUE THREAD

**Issue by wdongm** [avinassh/rockstar#67]
> > > from rockstar import RockStar
> > > rock_it_bro = RockStar(days=300)
> > > rock_it_bro.make_me_a_rockstar()//started going wrong

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\git\cmd.py", line 573, in execute
    **subprocess_kwargs
  File "C:\Python34\lib\subprocess.py", line 859, in **init**
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] System can not find the file specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\rockstar\RockStar.py", line 81, in make_m
_a_rockstar
    self.repo = git.Repo.init(self.repo_path)
  File "C:\Python34\lib\site-packages\git\repo\base.py", line 764, in init
    git.init(*_kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 440, in <lambda>
    return lambda *args, *_kwargs: self._call_process(name, _args, *_kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 810, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 576, in execute
    raise GitCommandNotFound(str(err))
git.exc.GitCommandNotFound: [WinError 2] System can not find the file specified.

somebody can help me ,thx

**Comment by avinassh** [comment]
ayy, you need git installed.

**Comment by wdongm** [comment]
I have been create a git repository,but where to find the current directory. could you tell me how to find it.thank you so much!

**Comment by wangdongming007** [comment]
how to push the local repo to a github.

**Comment by wdongm** [comment]
how to push the local repo to a github.never use the git before.could you tell me how to do that.or give me the link ,thank you so much!

**Comment by ohnx** [comment]
Create a new repository on GitHub.
`git init`
run rockstar
`git remote add origin https://github.com/wangdongming007/<respository name>.git`
`git push -u origin master`
Enter your username and password.
done.

**Comment by wdongm** [comment]
HI @ohnx  thank you for your detailed guide.But,i still has some confuses on that step.
i use the  git cmd  to do the follow.

Create a new repository on GitHub.  
 //https://github.com/wangdongming007/learn-CPP

git init 
 //Reinitialized existing Git repository in C:/Users/Code_ming/.git/      (use git cmd)

run rockstar
//this step i was confuse ,is it run rockstar in git cmd again?

git remote add origin https://github.com/wangdongming007/<respository name>.git  
//https://github.com/wangdongming007/<learn-CPP>.git

git push -u origin master
Enter your username and password.
done.

if you know ,pleae tell me some more detailed,anyway,thank you so much!

**Comment by ohnx** [comment]
By 'run rockstar', I mean execute whatever python script using rockstar in that directory.
