### ISSUE TITLE
Not much of a rockstar here 

### ISSUE THREAD

**Issue by hsavit1** [avinassh/rockstar#7]
can anyone tell me where im going wrong?

running python 3.4

when i run the example module.... i get an error like this

Traceback (most recent call last):
  File "/Users/user/Desktop/rockstar/example.py", line 1, in <module>
    from RockStar import RockStar
  File "/Users/user/Desktop/rockstar/RockStar/**init**.py", line 9, in <module>
    import git
ImportError: No module named 'git'

**Comment by hsavit1** [comment]
had to fix my path to 3.4, nevermind

**Comment by Squarific** [comment]
Are you sure its 3.4?

Nvm, see you fixed it.

**Comment by avinassh** [comment]
You are half Rockstar now, run the damn thing!

**Comment by hsavit1** [comment]
still trying to fix my path lol !

**Comment by avinassh** [comment]
I think requirements are not getting installed

**Comment by hsavit1** [comment]
right @avinassh , because my path is stuck with python 2.7, it is not installing it (which requires python 3)

**Comment by avinassh** [comment]
Umm... Create `virtualenv` with Python 3?

```
virtualenv venv --python=`which python3`
```
