### ISSUE TITLE
Make it skip some days randomly

### ISSUE THREAD

**Issue by sahildua2305** [avinassh/rockstar#79]
Idea - it can take float parameter from user and that will be the fraction of days that user wants to skip randomly from the total number of days user has mentioned.

I can take it up immediately. Just want to make sure, you are still maintaining it and merging PRs @avinassh

**Comment by avinassh** [comment]
I am still maintaining it, go ahead send a PR ;)

**Comment by sahildua2305** [comment]
Why to close the issue when this feature isn't implemented yet? Rather you should have tagged it with 'enhancement'

**Comment by avinassh** [comment]
because I already merged your PR #80?

**Comment by sahildua2305** [comment]
Okay. Sorry. I hadn't received that notification by then.

**Comment by avinassh** [comment]
👍
