### ISSUE TITLE
"from: can't read /var/mail/rockstar"

### ISSUE THREAD

**Issue by jpvalery** [avinassh/rockstar#85]
Hey,

Tried playing with this but getting this error when typing 

I've done `sudo pip install rockstar` and all requirements are satisfied.
I've also installed python 3.6, and gitpython. 

So I'm doing `git init` then cd to ~/.git/
There trying to `from rockstar import RockStar` and getting the error `from: can't read /var/mail/rockstar`. 

Any idea of what I'm f*cking up ?

**Comment by avinassh** [comment]
you shouldn't do this: 

```
cd to ~/.git/
```

Quick instructions:

1. Create virtualenv 
2. Install rockstar
3. try running the script

**Comment by jpvalery** [comment]
Thanks for your fast reply. 

Created a virtualenv, installed rockstar in it, ran it - It completed 
`Making you a Rockstar Programmer  [####################################]  100%          

You are now a Rockstar Programmer!
>>> `
However I can't seem to find the folder where the files would be to push them to github ?

**Comment by avinassh** [comment]
So I guess, it worked?

**Comment by jpvalery** [comment]
The script most certainly did - but I can't find the folder to push it to GitHub. What am I missing ?

**Comment by avinassh** [comment]
the current directory? As the README says:

> Above script will create a git repository in the current directory. After that, create a repo on Github and push the local repo. That's all!

**Comment by jpvalery** [comment]
OK I hadn't thought to check a .git folder - thought it'd be another name. Just me being a dumbass.

Thanks for the help @avinassh !
