### ISSUE TITLE
cannot import name 'Rockstar' from partially initialized module 'rockstar'

### ISSUE THREAD

**Issue by gautamhans1** [avinassh/rockstar#98]
ImportError: cannot import name 'RockStar' from partially initialized module 'rockstar' (most likely due to a circular import)

**Comment by pcaversaccio** [comment]
This happens if you name a python file the same name as a dependency your project uses. Thus, if you saved the following lines as `rockstar.py` it won't work:
```
from rockstar import RockStar

rock_it_bro = RockStar(days=300)
rock_it_bro.make_me_a_rockstar()
```
Rename the file and it will compile.

**Comment by avinassh** [comment]
@pcaversaccio thank you! I guess thats what was happening.
